const menuButton=document.querySelector('.menu-toggle');
const mobileNav=document.querySelector('#mobile-nav');
const setInert=value=>{document.querySelector('main').inert=value;document.querySelector('footer').inert=value;};
const closeMenu=()=>{setInert(false);mobileNav.hidden=true;menuButton.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open');};
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';mobileNav.hidden=!open;setInert(open);menuButton.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open);if(open)mobileNav.querySelector('a').focus();});
mobileNav?.addEventListener('click',e=>{const link=e.target.closest('a');if(link){closeMenu();const dest=new URL(link.href);if(dest.pathname===location.pathname&&dest.hash){const target=document.querySelector(dest.hash);if(target){target.setAttribute('tabindex','-1');target.focus({preventScroll:true});}}}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!mobileNav.hidden){closeMenu();menuButton.focus();}hideBubble();}if(e.key==='Tab'&&!mobileNav.hidden){const links=[menuButton,...mobileNav.querySelectorAll('a')];const first=links[0],last=links.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
matchMedia('(min-width:768px)').addEventListener('change',e=>{if(e.matches)closeMenu();});
const form=document.querySelector('#project-form');
if(form){const name=form.querySelector('#name'),subject=form.querySelector('#subject'),message=form.querySelector('#message'),preview=form.querySelector('#message-preview');const selected=new URLSearchParams(location.search).get('sujet');if([...subject.options].some(o=>o.value===selected))subject.value=selected;const compose=()=>`Bonjour,${name.value.trim()?' je m’appelle '+name.value.trim()+'.':''}\nJe souhaite vous contacter au sujet de : ${subject.value}.\n${message.value.trim()?'\n'+message.value.trim()+'\n':''}\nMerci et à bientôt.`;const update=()=>{preview.textContent=compose();};form.addEventListener('input',update);update();form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const target=new URL(document.querySelector('.whatsapp').href);target.searchParams.set('text',compose());window.open(target.href,'_blank','noopener');document.querySelector('#form-status').textContent='Votre message est prêt. Envoyez-le dans WhatsApp pour contacter Lucane.';document.dispatchEvent(new CustomEvent('lucane:conversion',{detail:{action:'whatsapp_open',page:location.pathname}}));});}
const bubble=document.querySelector('.contact-bubble');function hideBubble(){if(bubble)bubble.hidden=true;try{sessionStorage.setItem('lucane-contact-seen','1');}catch{}}
bubble?.querySelector('button').addEventListener('click',hideBubble);let shown=false;try{shown=sessionStorage.getItem('lucane-contact-seen')==='1';}catch{}
const offerContact=()=>{if(shown||!bubble)return;if(document.hidden||document.body.classList.contains('menu-open')||document.body.classList.contains('field-active')){setTimeout(offerContact,2500);return;}bubble.hidden=false;shown=true;try{sessionStorage.setItem('lucane-contact-seen','1');}catch{}};setTimeout(offerContact,5000);
document.addEventListener('focusin',e=>{document.body.classList.toggle('field-active',e.target.matches('input,textarea,select'));});document.addEventListener('focusout',()=>{setTimeout(()=>document.body.classList.toggle('field-active',document.activeElement?.matches('input,textarea,select')),0);});

const opening=document.querySelector('.orbital-hero');if(opening)new IntersectionObserver(([entry])=>document.body.classList.toggle('hero-visible',entry.isIntersecting)).observe(opening);
